/*==============================================================================
= DATABASE SETTINGS
==============================================================================*/
set database sql syntax PGS true;

set database default table type cached;

/*====================================================================================================
= SEQUENCES
=====================================================================================================*/
create sequence resource_id as bigint start with 1;

create sequence revision_id as bigint start with 1;

create sequence search_param_id as bigint start with 1;

/*====================================================================================================
= TABLES
=====================================================================================================*/
create table resource (
    id bigint generated by default as sequence resource_id primary key,
    version bigint not null,
    spec_type varchar(64) not null,
    type varchar(64) not null,
    content clob(10485760) not null,
    text clob(10485760)
);

create table resource_history (
    revision_id bigint not null,
    revision_type tinyint not null,
    revision_end_id bigint,
    revision_end_timestamp timestamp with time zone,
    id bigint not null,
    version bigint,
    spec_type varchar(64) not null,
    type varchar(64),
    content clob(10485760),
    text clob(10485760),
    primary key (id, revision_id)
);

create table revision (
    id bigint generated by default as sequence revision_id primary key,
    timestamp timestamp with time zone not null
);

create table search_param_date (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value_start timestamp with time zone,
    value_end timestamp with time zone
);

create table search_param_number (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value decimal not null
);

create table search_param_quantity (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    code_system_uri varchar(1024),
    code_system_version varchar(64),
    units varchar(128),
    display_name varchar(256),
    value decimal not null
);

create table search_param_ref (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value varchar(1024) not null
);

create table search_param_string (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value clob(1048576) not null
);

create table search_param_token (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    code_system_uri varchar(1024),
    code_system_version varchar(64),
    display_name varchar(256),
    value varchar(128) not null
);

create table search_param_uri (
    id bigint generated by default as sequence search_param_id primary key,
    resource_id bigint not null,
    resource_version bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value varchar(1024) not null
);
