/*==============================================================================
= DATABASE SETTINGS
==============================================================================*/
set database sql syntax PGS true;

set database default table type cached;

/*==============================================================================
= USERS
==============================================================================*/
create user "${sdcct.data.db.user.main.name}" password '${sdcct.data.db.user.main.pass}';

/*====================================================================================================
= SEQUENCES
=====================================================================================================*/
create sequence search_param_entity_id as bigint start with 1;

grant usage on sequence search_param_entity_id to "${sdcct.data.db.user.main.name}";

create sequence resource_entity_id as bigint start with 1;

grant usage on sequence resource_entity_id to "${sdcct.data.db.user.main.name}";

/*====================================================================================================
= TABLES
=====================================================================================================*/
create table search_param_coord (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    latitude double not null,
    longitude double not null
);

grant select, insert, update, delete on table search_param_coord to "${sdcct.data.db.user.main.name}";

create table search_param_date (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value timestamp not null
);

grant select, insert, update, delete on table search_param_date to "${sdcct.data.db.user.main.name}";

create table search_param_num (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value blob(1048576) not null
);

grant select, insert, update, delete on table search_param_num to "${sdcct.data.db.user.main.name}";

create table search_param_quantity (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value blob(1048576) not null,
    code_system_uri varchar(1024),
    units varchar(1024)
);

grant select, insert, update, delete on table search_param_quantity to "${sdcct.data.db.user.main.name}";

create table search_param_ref (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value varchar(1024) not null
);

grant select, insert, update, delete on table search_param_ref to "${sdcct.data.db.user.main.name}";

create table search_param_str (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value clob(1048576) not null
);

grant select, insert, update, delete on table search_param_str to "${sdcct.data.db.user.main.name}";

create table search_param_token (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value varchar(64) not null,
    code_system_uri varchar(1024)
);

grant select, insert, update, delete on table search_param_token to "${sdcct.data.db.user.main.name}";

create table search_param_uri (
    entity_id bigint generated by default as sequence search_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    name varchar(64) not null,
    value varchar(1024) not null
);

grant select, insert, update, delete on table search_param_uri to "${sdcct.data.db.user.main.name}";

create table form_fhir (
    entity_id bigint generated by default as sequence resource_entity_id primary key,
    id varchar(64) not null,
    type varchar(64) not null,
    content clob(10485760) not null,
    text clob(1048576)
);

grant select, insert, update, delete on table form_fhir to "${sdcct.data.db.user.main.name}";

create table form_rfd (
    entity_id bigint generated by default as sequence resource_entity_id primary key,
    id varchar(64) not null,
    type varchar(64) not null,
    content clob(10485760) not null
);

grant select, insert, update, delete on table form_rfd to "${sdcct.data.db.user.main.name}";

create table form_resp_fhir (
    entity_id bigint generated by default as sequence resource_entity_id primary key,
    id varchar(64) not null,
    type varchar(64) not null,
    content clob(10485760) not null,
    text clob(1048576)
);

grant select, insert, update, delete on table form_resp_fhir to "${sdcct.data.db.user.main.name}";

create table form_resp_rfd (
    entity_id bigint generated by default as sequence resource_entity_id primary key,
    id varchar(64) not null,
    type varchar(64) not null,
    content clob(10485760) not null
);

grant select, insert, update, delete on table form_resp_rfd to "${sdcct.data.db.user.main.name}";
