/*==============================================================================
= DATABASE SETTINGS
==============================================================================*/
set database sql syntax PGS true;

set database default table type cached;

/*====================================================================================================
= SEQUENCES
=====================================================================================================*/
create sequence resource_entity_id as bigint start with 1;

create sequence resource_param_entity_id as bigint start with 1;

/*====================================================================================================
= TABLES
=====================================================================================================*/
create table resource (
    entity_id bigint generated by default as sequence resource_entity_id primary key,
    entity_version bigint not null,
    id bigint not null,
    instance_id bigint not null,
    version bigint not null,
    spec_type varchar(64) not null,
    type varchar(64) not null,
    deleted_timestamp timestamp with time zone,
    modified_timestamp timestamp with time zone not null,
    published_timestamp timestamp with time zone not null,
    content clob(${sdcct.data.db.entity.resource.content.size.max}) not null,
    text clob(${sdcct.data.db.entity.resource.text.size.max}),
    unique (id, instance_id, version)
);

create table resource_param_date (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    value_start timestamp with time zone,
    value_end timestamp with time zone
);

create table resource_param_number (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    value decimal not null
);

create table resource_param_quantity (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    code_system_uri varchar(1024),
    code_system_version varchar(64),
    units varchar(128),
    display_name varchar(256),
    value decimal not null
);

create table resource_param_ref (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    value varchar(1024) not null
);

create table resource_param_string (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    value clob(1048576) not null
);

create table resource_param_token (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    code_system_uri varchar(1024),
    code_system_version varchar(64),
    display_name varchar(256),
    value varchar(128) not null
);

create table resource_param_uri (
    entity_id bigint generated by default as sequence resource_param_entity_id primary key,
    resource_entity_id bigint not null,
    type varchar(64) not null,
    meta boolean not null,
    name varchar(64) not null,
    value varchar(1024) not null
);

/*====================================================================================================
= INDEXES
=====================================================================================================*/
create index resource_instance_id on resource(instance_id);

create index resource_spec_type on resource(spec_type);

create index resource_version on resource(version);

create index resource_param_date_value_start_value_end on resource_param_date(value_start, value_end);

create index resource_param_number_value on resource_param_number(value);

create index resource_param_quantity_value on resource_param_quantity(value);

create index resource_param_ref_value on resource_param_ref(value);

create index resource_param_string_value on resource_param_string(value);

create index resource_param_token_value on resource_param_token(value);

create index resource_param_uri_value on resource_param_uri(value);
